### PR TITLE
Move error logging from wireguard-go package to application service.

### PR DESCRIPTION
**Pull request by drgkaleda**
Passing errors from package up to log (or take some actions) in higher level

Signed-off-by: Antanas Gadeikis <antanas.gadeikis@nordsec.com>

### CODE REVIEW

**Comment by drgkaleda** [comment]
Releated: https://github.com/WireGuard/wireguard-go/pull/46

**Comment by zx2c4** [comment]
What's the motivation for this change? Have you found that reboots are actually sometimes necessary? In that case, do you have a reproducer?

**Comment by drgkaleda** [comment]
Motivation for that is not to hide required reboots deep in the package, but to inform the caller directly.
The projects count, that are using wireguard-go as submodule, is increasing.
And I think its better for a submodule to pass all needed information to upper layer, instead of silently "hiding" them in debug logger.
I think the caller should be directly informed that reboot is required, instead of parsing log stream for a speciffic message.

P.S.
No. I have not encountered a reboot required yet. But if OS has such return value - I believe it is possible to happen.

**Comment by drgkaleda** [comment]
Maybe I shoud update the pull request and move reboot required log message to CreateTun function ?
In that case if somebody's using interface function CreateTUN - they will have the reboot required message in log.
And project that can handle rebootRequired - will get that information directly.

**Comment by drgkaleda** [comment]
One more note:

this pull request was the sequel of this one:
https://github.com/WireGuard/wireguard-go/pull/46

**Comment by zx2c4** [comment]
So just to confirm -- you _haven't_ actually seen this cropping up anywhere?

I ask because we've worked super hard to make Wintun never actually trigger that condition, which is why it's merely only logged rather than returned for something programmatic. We don't think this is actually something developers should be required to handle.

So if you are having to handle it, that's an important piece of information, and I'd like to hear more about _that_ so we can see if there's a bug happening somewhere.

**Comment by drgkaleda** [comment]
Closing this PR as unneeded.

**Pull request closed without merging**
